import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ar" | "en";

interface LanguageContextProps {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
  isRtl: boolean;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const arabicToEnglish: Record<string, string> = {
  // Common UI / Header
  "لوحة الأداء": "Performance Dashboard",
  "لوحة الإدارة": "Admin Panel",
  "الأداء الأسبوعي": "Weekly Performance",
  "أداء قادة المجموعات": "Team Leaders Performance",
  "التحليلات العامة": "General Analytics",
  "تسجيل الخروج": "Logout",
  "توقيت القاهرة:": "Cairo Time:",
  "سيرفر WE متصل": "WE Server Connected",
  "تفعيل الوضع النهاري": "Light Mode",
  "تفعيل الوضع الليلي": "Dark Mode",
  "جاري الاتصال بقاعدة بيانات وي (WE)...": "Connecting to WE database...",
  "لوحة الأداء الشهري للموظفين": "Employees Monthly Performance Dashboard",
  "الرجاء اختيار أحد الموظفين": "Please select an employee",
  "استعمل قائمة البحث في الجانب الأيمن لاستعراض تفاصيل أدائه": "Use the search column to browse their performance details",
  "تقرير الأداء والتقييم الفردي للموظف": "Employee Individual Performance & Evaluation Report",
  "تصدير PDF": "Export PDF",
  "تصدير الصفحة الحالية لملف PDF": "Export current page as PDF",
  "الشهر المراد عرضه:": "Selected Month:",
  "الشهر المراد عرضه": "Month to show",
  "كارت الأداء التاريخي (Excel)": "Historical Scorecard (Excel)",
  "المنحنيات والتحليلات": "Trends & Analytics",
  "لوحة الأداء الشهري": "Monthly Performance Board",
  "الاسم:": "Name:",
  "كود الموظف:": "Employee Code:",
  "الموقع:": "Location:",
  "قائد المجموعة:": "Team Leader:",
  "المشرف:": "Supervisor:",
  "قطاع العمل:": "Line of Business (LOB):",
  "الرقم القومي:": "National ID:",
  "رقم الموبايل:": "Mobile Number:",
  "الهدف:": "Target:",
  "الهدف": "Target",
  "الهدف الكلي": "Overall Target",
  "متوسط تقييم الأداء العام": "Average Overall Performance",
  "معدل رضا العملاء (CSI)": "Customer Satisfaction (CSI)",
  "مؤشر صافي الترويج (NPS)": "Net Promoter Score (NPS)",
  "متوسط وقت المعالجة (AHT)": "Average Handling Time (AHT)",
  "سجل التقييمات": "Evaluations Log",
  "شهر": "Month",
  "مستهدف الأداء العام للموظف": "Overall Employee Performance Target",
  "معدل تحقيق الكفاءة": "Efficiency Achievement Rate",
  "الهدف الأداء الشهري العام:": "Overall Monthly Performance Target:",
  "أداء الموظف ممتاز ويتجاوز التوقعات!": "Employee performance is excellent and exceeds expectations!",
  "أداء الموظف ممتاز ويحقق الأهداف.": "Employee performance is excellent and meets targets.",
  "أداء الموظف مقبول ولكنه قريب من الحد الأدنى.": "Employee performance is acceptable but close to the minimum limit.",
  "أداء الموظف ضعيف ويحتاج إلى خطة تحسين عاجلة.": "Employee performance is poor and needs an urgent improvement plan.",
  "معدل تحقيق المستهدفات الفردية": "Individual Target Achievement Rate",
  "مؤشرات الحضور والغياب (Leaves)": "Attendance & Leave Indicators (Leaves)",
  "غياب": "Absent",
  "مرضي": "Sick",
  "طارئ": "Emergency",
  "غير مخطط": "Unplanned",
  "CSI (رضا العملاء)": "CSI (Customer Satisfaction)",
  "NPS (مؤشر التوصية)": "NPS (Net Promoter Score)",
  "FCR (حل من أول مرة)": "FCR (First Contact Resolution)",
  "TTB (أعلى نتيجتين)": "TTB (Top Two Boxes)",
  "AHT (وقت المعالجة)": "AHT (Average Handling Time)",
  "CTC (أهمية للعميل)": "CTC (Critical to Customer)",
  "CTB (أهمية للعمل)": "CTB (Critical to Business)",
  "كلما قل الوقت تحسن الأداء": "Lower time indicates better performance",
  "نسبة الإنجاز:": "Achievement Rate:",
  "نسبة الإنجاز": "Achievement Rate",
  "تحقيق المستهدف": "Target Achieved",
  "الأداء التاريخي للموظف": "Employee Historical Performance",
  "أداء الموظف ومستوى تحقيق المستهدفات عبر الأشهر": "Employee performance and target achievements over months",
  "الدرجة النهائية": "Final Score",
  "تحليل منحنيات الأداء": "Performance Trends Analysis",
  "تطور الأداء ومستوى رضا العملاء عبر الأشهر": "Performance development and customer satisfaction over months",
  "منحنى رضا العملاء (CSI)": "Customer Satisfaction (CSI) Trend",
  "منحنى الأداء العام": "Overall Performance Trend",
  "منحنى وقت المعالجة (AHT)": "Handling Time (AHT) Trend",
  "المستهدف": "Target",
  "الدرجة الفردية": "Individual Score",

  // Search / Sidebar
  "البحث عن موظف": "Search for Employee",
  "اكتب اسم الموظف أو الكود (ID) ...": "Type employee name or ID...",
  "لا توجد نتائج مطابقة لبحثك.": "No results matched your search.",
  "قائد الفريق (TL)": "Team Leader (TL)",
  "المشرف (SV)": "Supervisor (SV)",
  "مقر العمل": "Workplace",
  "رقم الهاتف": "Phone Number",
  "رقم الهوية": "National ID",
  "تصفية حسب الموقع": "Filter by Location",
  "تصفية حسب LOB": "Filter by LOB",
  "مجموعات العمل": "Working Groups",
  "مؤرشف": "Archived",
  "نشط": "Active",
  "بحث عن قائد مجموعة أو مشرف...": "Search for TL or SV...",

  // Weekly performance
  "لوحة الأداء الأسبوعي للموظفين": "Employees Weekly Performance Dashboard",
  "البحث في الأداء الأسبوعي": "Search Weekly Performance",
  "مقارنة الأسابيع وتحليل الاستجابة": "Weekly Comparison & Response Analysis",
  "منحنى الأداء الأسبوعي للموظف": "Employee Weekly Performance Trend",
  "درجة الأداء": "Performance Score",
  "كارت الأداء الأسبوعي": "Weekly Scorecard",
  "كود الموظف": "Employee ID",
  "الاسم": "Employee Name",
  "الأسبوع": "Week",
  "المكالمات المجابة": "Answered Calls",
  "AHT": "AHT",
  "NPS": "NPS",
  "FCR": "FCR",
  "TTB": "TTB",
  "BB": "BB",
  "الأسبوع 1": "Week 1",
  "الأسبوع 2": "Week 2",
  "الأسبوع 3": "Week 3",
  "الأسبوع 4": "Week 4",
  "الأسبوع الأول": "First Week",
  "الأسبوع الثاني": "Second Week",
  "الأسبوع الثالث": "Third Week",
  "الأسبوع الرابع": "Fourth Week",
  "مجمع (الكل)": "Aggregate (All)",
  "مقارنة الأداء": "Performance Comparison",
  "مقارنة أداء الأسابيع": "Weekly Performance Comparison",
  "تصفية النتائج": "Filter Results",
  "الكل": "All",
  "بدون": "None",
  "العمل من المنزل (WFH)": "Work From Home (WFH)",
  "مقر مدينة نصر (NC)": "Nasr City Office (NC)",
  "مقر الدقي (Dokki)": "Dokki Office (Dokki)",
  "استعمل قائمة البحث في الجانب الأيمن لاستعراض تفاصيل الأداء الأسبوعي": "Use the search list on the right side to review weekly performance details.",
  "تفاصيل الأداء": "Performance Details",
  "تطور الأداء خلال الشهر": "Performance Trend During Month",
  "Answered (الردود)": "Answered (Replies)",
  "AHT (سرعة الرد)": "AHT (Average Handling Time)",
  "TNPS (مؤشر التوصية)": "TNPS (Recommendation Index)",
  "FCR (الحل من أول مرة)": "FCR (First Contact Resolution)",
  "TTB (الأساسيات)": "TTB (Basics)",
  "BB (الخصومات)": "BB (Penalties)",
  "تقرير الأداء الأسبوعي للموظف": "Employee's Weekly Performance Report",
  "اسم الموظف:": "Employee Name:",
  "كود الموظف (ID):": "Employee Code (ID):",
  "قائد الفريق (TL):": "Team Leader (TL):",
  "المشرف (Supervisor):": "Supervisor (Supervisor):",
  "الخط (LOB):": "Line of Business (LOB):",
  "لا توجد بيانات لهذا الأسبوع": "No data available for this week",
  "إجمالي": "Total",
  "يرجى فتح التطبيق في علامة تبويب جديدة مستقلة (Open App) من الزر العلوي في شريط منصة AI Studio.": "Please open the application in a new independent tab (Open App) from the top button of the AI Studio panel.",
  "بمجرد فتح الرابط في نافذة جديدة، اضغط على زر \"تصدير PDF\" مجدداً وسيفتح لك المتصفح خيارات الحفظ الفوري كملف PDF فائق ومثالي للطباعة!": "Once the link is opened in a new window, click the \"Export PDF\" button again, and the browser will open instant save options as a high-quality PDF perfect for printing!",
  "(TL) قائد الفريق": "Team Leader (TL)",
  "(Supervisor) المشرف": "Supervisor (Supervisor)",

  // Leaders performance
  "أداء قادة المجموعات (TLs)": "Team Leaders (TLs) Performance Board",
  "استعراض أداء قادة المجموعات والمشرفين ومعدل تحقيق مستهدفاتهم": "Review Team Leaders' & Supervisors' performance and target achievements",
  "البحث عن قائد أو مشرف...": "Search for Team Leader or Supervisor...",
  "تصفية حسب المشرف (SV)": "Filter by Supervisor (SV)",
  "قائد المجموعة (TL)": "Team Leader (TL)",
  "المشرف": "Supervisor",
  "متوسط رضا العملاء": "Average CSI",
  "معدل الحضور": "Attendance Rate",
  "معدل الالتزام": "Adherence Rate",
  "أداء قادة الفرق": "Team Leaders Performance",
  "الأداء التاريخي لقائد المجموعة": "Team Leader Historical Performance",
  "تطور أداء قادة المجموعات عبر الأشهر": "Team Leaders' performance development over months",

  // Analytics
  "التحليلات المتقدمة لمؤشرات الأداء": "Advanced Performance Indicators Analytics",
  "استعراض إحصائيات عامة وتوزيع الأداء والمقارنات": "Review general stats, performance distribution, and comparisons",
  "أفضل الموظفين أداءً": "Top Performing Employees",
  "أقل الموظفين أداءً": "Lowest Performing Employees",
  "توزيع تقييمات الموظفين": "Employee Evaluations Distribution",
  "مقارنة أداء مواقع العمل (WFH vs Site)": "Workplace Performance Comparison (WFH vs Site)",
  "متوسط التقييم العام": "Overall Average Score",
  "الموظفون الأكثر تميزاً": "Distinguished Employees",
  "الموظفون الذين يحتاجون دعم": "Employees Needing Support",
  "عدد الموظفين": "Number of Employees",
  "متوسط تقييم الأداء": "Average Performance Evaluation",
  "متوسط CSI": "Average CSI",
  "متوسط NPS": "Average NPS",
  "تطور الأداء العام للقطاع": "Sector Overall Performance Trend",

  // Admin Panel
  "لوحة تحكم المشرفين والإدارة": "Supervisors & Admins Control Panel",
  "إدارة مستخدمي النظام": "System Users Management",
  "إضافة مستخدم جديد": "Add New User",
  "إدارة الموظفين وهيكل العمل": "Employees & Structure Management",
  "إضافة موظف جديد": "Add New Employee",
  "تحديث المستهدفات السنوية والشهرية": "Update Annual & Monthly Targets",
  "إرسال تنبيه / إعلان عام": "Send Alert / Public Announcement",
  "تصدير البيانات واستيرادها": "Data Export & Import",
  "اسم المستخدم الفردي": "Individual Username",
  "الاسم الكامل": "Full Name",
  "الدور الوظيفي": "System Role",
  "الصلاحيات الممنوحة": "Permissions Granted",
  "حفظ التغييرات": "Save Changes",
  "إلغاء": "Cancel",
  "تأكيد": "Confirm",
  "إضافة": "Add",
  "تعديل": "Edit",
  "حذف": "Delete",
  "الأدوار": "Roles",
  "الصلاحيات": "Permissions",
  "نوع الخطأ": "Error Type",
  "الرقم القومي": "National ID",
  "رقم الموبايل": "Mobile Number",
  "الموقع": "Location",
  "LOB": "LOB",
  "حفظ": "Save",
  "إغلاق": "Close",
  "بحث": "Search",
  "تحديث": "Update",
  "مستهدف CSI": "CSI Target",
  "مستهدف NPS": "NPS Target",
  "مستهدف FCR": "FCR Target",
  "مستهدف TTB": "TTB Target",
  "مستهدف AHT (بالثواني)": "AHT Target (in seconds)",
  "مستهدف CTC": "CTC Target",
  "مستهدف CTB": "CTB Target",
  "مستهدف الأداء العام": "Overall Target Score",
  "عنوان الإعلان": "Announcement Title",
  "محتوى الرسالة / الإعلان": "Message / Announcement Content",
  "الفئة المستهدفة": "Target Audience",
  "إرسال الإعلان": "Send Announcement",
  "مدير": "Manager",
  "قائد مجموعة": "Team Leader",
  "أدمن": "Admin",
  "أخرى": "Other",

  // Auth / Login
  "تسجيل الدخول لبوابة وي": "Sign in to WE Portal",
  "الرجاء إدخال اسم المستخدم وكلمة المرور": "Please enter your username and password",
  "اسم المستخدم": "Username",
  "كلمة المرور": "Password",
  "تسجيل الدخول": "Sign In",
  "اسم المستخدم أو كلمة المرور غير صحيحة": "Incorrect username or password",
  "أدخل اسم المستخدم": "Enter username",
  "أدخل كلمة المرور": "Enter password",

  // Notifications
  "أحدث التنبيهات والتعميمات": "Latest Alerts & Circulars",
  "تنبيه هام": "Important Alert",
  "عرض الكل": "Show All",
  "تنبيهات": "Alerts",
  "تنبيه": "Alert",
  "الرسائل": "Messages",
  "تنبيه جديد": "New Alert",

  // Maintenance & Misc
  "الصفحة قيد الصيانة": "Page Under Maintenance",
  "هذه الصفحة تخضع لعمليات صيانة وتحديث حالياً لتوفير أفضل تجربة مستخدم.": "This page is currently undergoing maintenance and updates to provide the best user experience.",
  "العودة للرئيسية": "Back to Home",
  "بدون ليدر": "No Leader",
  "مستهدف": "Target",
  "أيام العمل": "Working Days",
  "سيرفر متصل": "Server Connected",
  "سيرفر WE متصل وقاعدة البيانات نشطة": "WE Server is connected and database is active",
  "سيرفر وي": "WE Server",
  "نشط الآن": "Active Now",
  "مستخدم": "User",
  "مستخدمين": "Users",
  "متصل الآن": "Online Now",
  "قاعدة البيانات متصلة": "Database Connected",
  "الموقع متصل بالكامل بقاعدة بيانات السحابية": "Fully connected to Firestore Cloud Database",
  "غير متصل": "Disconnected",

  // New keys for EmployeeDashboard and other parts
  "التقييم العام النهائي - ": "Final Overall Score - ",
  "التقييم العام النهائي": "Final Overall Score",
  "متخطي الهدف (ناجح)": "Exceeds Target (Successful)",
  "أقل من النسبة المطلوبة": "Below Required Percentage",
  "ملخص أداء الشهر الحالي": "Current Month Performance Summary",
  "سرعة الرد الإجمالية (AHT)": "Overall Response Speed (AHT)",
  "رضا العملاء (CSI)": "Customer Satisfaction (CSI)",
  "مؤشر التوصية (NPS)": "Net Promoter Score (NPS)",
  "حل الشكوى أول مرة (FCR)": "First Contact Resolution (FCR)",
  "CTC (أهمية للشركة)": "CTC (Critical to Customer)",
  "CTB (أهمية للشركة)": "CTB (Critical to Business)",
  "لم تسجل بيانات لهذا الشهر بعد": "No performance data recorded for this month yet",
  "منحنى تطور التقييم النهائي (%) عبر الأشهر": "Final Score (%) Trend Over Months",
  "تحتاج إلى إدخال بيانات شهرين على الأقل لرسم المنحنى": "You need to enter at least two months of data to draw the trend",
  "مقارنة مؤشرات رضا العملاء (CSI) و (NPS) شهرياً": "Monthly CSI & NPS Metrics Comparison",
  "تحتاج لبيانات شهرين على الأقل لإظهار المقارنة": "You need at least two months of data to display the comparison",
  "رضا العملاء CSI": "Customer Satisfaction CSI",
  "مؤشر التوصية NPS": "Net Promoter Score NPS",
  "متوسط الأداء التاريخي لهذا الموظف": "Historical Average Performance for this Employee",
  "معدل التقييم التراكمي": "Cumulative Evaluation Rate",
  "مقارنة بالهدف": "Compared to Target",
  "الهدف المطلوب:": "Required Target:",
  "متوسط رضا العملاء (CSI)": "Average Customer Satisfaction (CSI)",
  "عدد الأشهر المسجلة": "Number of Months Recorded",
  "تاريخ رصد الأداء المتواصل": "Continuous performance tracking history",
  "أشهر": "months",
  "كارت الأداء التفصيلي الشامل": "Comprehensive Detailed Scorecard",
  "مطابق تماماً لنموذج كشف شيت الاكسيل لمشروعات الشات والدعم الفني": "Perfectly matching the Excel sheet template for Chat and Technical Support projects",
  "التقييم التراكمي:": "Cumulative Evaluation:",
  "المؤشرات (KPIs)": "Key Performance Indicators (KPIs)",
  "AHT (سرعة المعالجة)": "AHT (Average Handling Time)",
  "FCR (الحل الأول)": "FCR (First Contact Resolution)",
  "Absent (الغياب أيام)": "Absent (Leave Days)",
  "Sick (المرضي)": "Sick Leave",
  "Emergency (الطارئ)": "Emergency Leave",
  "Unplanned (غير المخطط)": "Unplanned Absence",
  "Final Score (التقييم العام)": "Final Score (Overall Evaluation)",
  "* يتم احتساب Final Score بناء على مدخلات جودة وقت الرد، جودة الرصد، الـ CSI، الـ NPS والخصومات الإدارية.": "* The Final Score is calculated based on inputs of response time quality, monitoring quality, CSI, NPS, and administrative deductions.",
  "خط الرصد والهدف الإرشادي العام: 52% لعام 2025/2026": "Baseline and general target guidelines: 52% for 2025/2026",
  "تنبيه هام لتصدير التقرير PDF بنجاح": "Important Warning to Export PDF Report Successfully",
  "بسبب قيود المتصفح الأمنية داخل بيئة العرض التجريبية": "Due to browser security restrictions in the embedded playground",
  "عزيزي الموظف، نظراً لأنك تقوم باستعراض التطبيق داخل نافذة تجريبية مدمجة (iFrame) تابعة لمنصة التطوير، فإن المتصفح يمنع تشغيل الطباعة المباشرة تلقائياً للمحافظة على أمان الصفحة.": "Dear employee, since you are viewing this app within an embedded iFrame from the development workspace, the browser blocks automatic direct printing to preserve security.",
  "خطوات بسيطة وسريعة لتصدير PDF:": "Simple & quick steps to export PDF:",
  "أو خذ الرابط المباشر للمعاينة أدناه وافتحه في المتصفح الخاص بك:": "Or take the direct preview link below and open it in your browser:",
  "نسخ الرابط": "Copy Link",
  "فتح التطبيق في نافذة مستقلة": "Open App in New Tab",
  "إغلاق النافذة": "Close Window",
  "بوابة تقييم الكفاءات والأداء الرقمي لقطاع الدعم الفني والدردشة - المصرية للاتصالات": "Digital Chat & Tech Support Competency and Performance Portal - Telecom Egypt (WE)",
  "متواجد الآن": "Online Now",

  // Core Main Menu Tabs and Sections
  "التقييم الفردي": "Individual Performance",
  "تقارير تشغيل الفرق": "Team Dashboard",
  "تقييم التيم ليدر": "Team Leader Evaluation",

  // Leader Performance Evaluation Page
  "نظام استعراض تقييمات المشرفين الشهرية": "System for reviewing monthly supervisor evaluations",
  "ابحث برقم أو اسم الليدر...": "Search by TL ID or name...",
  "قائمة التيم ليدر": "Team Leaders List",
  "مشرف": "Supervisor",
  "الرجاء اختيار أحد المشرفين": "Please select a supervisor",
  "استعمل قائمة البحث لاستعراض تفاصيل الأداء الشهري": "Use the search list to review monthly performance details.",
  "بيانات الأداء الشهري للمشرف": "Supervisor's Monthly Performance Data",
  "لا توجد بيانات متاحة لهذا الشهر": "No data available for this month",
  "لم يتم تسجيل تقييم للمشرف": "No evaluation has been recorded for the supervisor",
  "في شهر": "in month",
  "تقييم المشرف - ": "Supervisor Evaluation - ",
  "الشركة المصرية للاتصالات - خدمة العملاء": "Telecom Egypt - Customer Service",
  "اسم المشرف": "Supervisor Name",
  "الكود الوظيفي": "Employee ID",
  "موقع العمل": "Workplace Location",
  "الشهر المختار": "Selected Month",
  "تطور الأداء الشهري (التاريخي)": "Monthly Performance Trend (Historical)",
  "للحصول على أفضل جودة للطباعة والتصدير، يرجى فتح التطبيق في نافذة جديدة بدلاً من نافذة العرض الحالية.": "To get the best print and export quality, please open the app in a new tab instead of the current preview.",
  "فتح في نافذة جديدة": "Open in New Tab",

  // Analytics Dashboard Page
  "تقارير وإحصائيات قائد الفريق والتشغيل": "Team Leader & Operations Reports and Stats",
  "تقييم جماعي ومؤشرات جودة الأداء العام للشركة": "Group evaluation & overall quality performance indicators of the company",
  "كل قادة الفرق": "All Team Leaders",
  "لا توجد بيانات كافية": "Not enough data",
  "الرجاء إدخال بيانات أو رفع شيت تقييم لشهر": "Please enter data or upload an evaluation sheet for month",
  "أولاً في لوحة التحكم لمشاهدة التحليل الجماعي.": "first in the Control Panel to view collective analysis.",
  "تقرير إحصائيات وأداء الفرق": "Teams Performance & Statistics Report",
  "بوابة Digital Chat KPI - قطاع الدعم الفني والدردشة الرقمية (WE)": "Digital Chat KPI Portal - Technical Support & Digital Chat Sector (WE)",
  "شهر التقرير:": "Report Month:",
  "تصفية القادة (TL):": "Filter Leaders (TL):",
  "كافة الفرق (All)": "All Teams (All)",
  "الموظفين النشطين": "Active Employees",
  "* الذين يمتلكون سجل تقييم لشهر": "* Who have an evaluation record for month",
  "متوسط الكفاءة العام": "Overall Average Competency",
  "المستهدف:": "Target:",
  "نسبة نجاح الفريق (KPI)": "Team Success Rate (KPI)",
  "* الموظفون المحققون للهدف المخصص لخط العمل (LOB)": "* Employees who achieved the target assigned to their Line of Business (LOB)",
  "إجمالي ردود الفعل الإيجابية بالدردشات": "Total positive feedback in chats",
  "لوحة شرف الأداء الثلاثية - شهر": "Triple Performance Honor Board - Month",
  "أفضل 3 عناصر حققوا أعلى تقييمات إجمالية متكاملة في هذا الشهر:": "Top 3 who achieved the highest overall integrated evaluations this month:",
  "التقييم الكلي": "Overall Evaluation",
  "معدلات الكفاءة حسب قادة الفرق (TL)": "Competency Rates by Team Leaders (TL)",
  " موظف حالي": " active employee",
  "تنبيهات جودة الأداء وحالات الدعم الفني المطلوبة (Coaching Alerts)": "Performance Quality Alerts & Required Coaching Cases",
  "مجموعة الموظفين الذين يقل معدلهم العام عن هدف العمل المخصص لخط العمل الخاص بهم وبحاجة لجلسات تطوير أداء:": "Employees whose overall average is below their assigned LOB target and need performance development sessions:",
  "التقييم": "Evaluation",
  "👏 مذهل! لا يوجد موظف تحت خط المستهدف هذا الشهر. جميع الكوادر ناجحة ومستوفية للشروط!": "👏 Amazing! No employees are below the target line this month. All staff are successful and compliant!",
  "مقارنة الأداء التاريخي للموظف": "Employee's Historical Performance Comparison",
  "إغلاق المخطط": "Close Chart",
  "تقييم الموظف": "Employee Evaluation",
  "المستهدف المطلوب": "Required Target",
  "قائمة الفريق بالكامل": "Full Team List",
  "انقر على أي موظف لعرض المخطط البياني التاريخي لأدائه": "Click on any employee to view their historical performance chart",
  " موظف": " Employee",
  "الموظف": "Employee",
  "قائد الفريق": "Team Leader",
  "خط العمل (LOB)": "Line of Business (LOB)",
  "التقييم النهائي": "Final Score",
  "يرجى فتح التطبيق في": "Please open the application in a",
  "علامة تبويب جديدة مستقلة (Open App)": "new independent tab (Open App)",
  "من الزر العلوي في شريط منصة AI Studio.": "from the top button in the AI Studio platform bar.",
  "بمجرد فتح الرابط في نافذة جديدة، اضغط على زر": "Once the link is opened in a new window, click the",
  "مجدداً وسيفتح لك المتصفح خيارات الحفظ الفوري كملف PDF فائق ومثالي للطباعة!": "button again, and the browser will open instant save options as a high-quality PDF perfect for printing!"
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Language>(() => {
    return (localStorage.getItem("app_lang") as Language) || "ar";
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("app_lang", newLang);
  };

  useEffect(() => {
    // Set text direction dynamically
    document.documentElement.dir = lang === "en" ? "ltr" : "rtl";
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string): string => {
    if (lang === "ar") return key;
    return arabicToEnglish[key] || key;
  };

  const isRtl = lang === "ar";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, isRtl }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
